### ISSUE TITLE
[FEAT] 디폴트 이미지 일괄 적용

### ISSUE THREAD

**Issue by neoneoneo123** [nbc-final-team2/ddaraogae#107]
💎 이슈 내용

아래 내용에 대한 디폴트 이미지를 일괄 적용해야합니다.
- 지도 이미지
- 강아지 썸네일
- 등..(더있으면)

layout.xml 에 셋팅을 해놓도록 합니다.

📖 참고 사항

Glide 상에서는 xml이 적용되지 않아, 기본적으로 layout의 xml에 디폴트 이미지를 적용해야 합니다.

**Comment by winteryy** [comment]
이미지가 있었다가 없어지는 경우도 생각하면 기기 내부에 디폴트 이미지를 만들어 두고
각종 이미지 url이 null이면 해당 이미지 적용하도록 하는 방향도 좋을 것 같습니당
