### ISSUE TITLE
[BUG] 강아지 추가 시 완료 버튼 연타할 경우 중복으로 추가됨

### ISSUE THREAD

**Issue by neoneoneo123** [nbc-final-team2/ddaraogae#159]
💎 문제 사항

- 강아지 추가 시 완료 버튼을 연타하면 강아지가 중복으로 추가됩니다.

🚨 문제 재현 방법

- [1] 강아지 추가 화면 진입
- [2] 정보 입력
- [3] 완료 버튼 연타

📝 시도해 본 것

- 아직 없음

📖 참고 사항

https://github.com/nbc-final-team2/ddaraogae/pull/158#pullrequestreview-2124550079

- 스샷
![image](https://github.com/nbc-final-team2/ddaraogae/assets/128209823/4f6b6aa3-caba-47b4-9862-fb3b99303e19)

**Comment by winteryy** [comment]
해당 부분은 loading ui 처리와 함께 해결될 것 같습니다!
