### ISSUE TITLE
[BUG] history 화면에서 산책 거리가 오표기 되는 건

### ISSUE THREAD

**Issue by neoneoneo123** [nbc-final-team2/ddaraogae#171]
💎 문제 사항

- 히스토리 탭으로 이동하여 봤을 때 산책 거리가 km임에도 m로 표시되고 있습니다.

🚨 문제 재현 방법

- [1] 실행 후 히스토리 화면으로 이동

📖 참고 사항

- 스샷

<img width="490" alt="image" src="https://github.com/nbc-final-team2/ddaraogae/assets/128209823/9daf6fdd-d1a1-4918-80cf-2b16660513e8">

⬆️ firebase store 상에 저장된 산책 거리가 4.5km 정도이나,

![image](https://github.com/nbc-final-team2/ddaraogae/assets/128209823/5165446b-a7cc-42c7-8b13-eac50e2dee3a)

⬆️ 앱에서는 4m로 표시되고 있습니다.

<img width="327" alt="image" src="https://github.com/nbc-final-team2/ddaraogae/assets/128209823/33519503-8ce3-495d-af8b-b4c7a318fd6c">

⬆️ 대략적으로 이동한 거리를 지도 상에서 측정해도 4km가 넘습니다!

**Comment by juseonghyun** [comment]
https://github.com/nbc-final-team2/ddaraogae/pull/190
위 PR에서 수정했지만, github 사용법 미숙으로 해당 이슈를 못 닫았기에 제가 임의로닫습니다.
