### ISSUE TITLE
[BUG] 가로화면 대응 되지 않는 곳들

### ISSUE THREAD

**Issue by winteryy** [nbc-final-team2/ddaraogae#181]
💎 문제 사항

- 로그인, 회원가입, 마이페이지 화면이 가로 모드 진입 시, 사용이 힘들정도로 레이아웃이 무너집니다

🚨 문제 재현 방법

- [1] 해당 화면에서, 가로 회전
- 
📝 시도해 본 것

📖 참고 사항

- 레이아웃 내에서 스크롤뷰를 적용해야 할 것 같습니다

[Screen_recording_20240619_211508.webm](https://github.com/nbc-final-team2/ddaraogae/assets/104819764/bb1536ad-2e0e-4a7c-8b2f-2ddc22ba468f)

[Screen_recording_20240619_211646.webm](https://github.com/nbc-final-team2/ddaraogae/assets/104819764/8d26e19d-be1c-4038-abe6-e4d8e30b10c5)

**Comment by juseonghyun** [comment]
https://github.com/nbc-final-team2/ddaraogae/pull/190
위 PR에서 수정했지만, github 사용법 미숙으로 해당 이슈를 못 닫았기에 제가 임의로닫습니다.
