### ISSUE TITLE
[FEAT] 최근 산책 몇 시간 전인지 UI 제공: 김찬교

### ISSUE THREAD

**Issue by theBettor** [nbc-final-team2/ddaraogae#221]
💎 개발할 기능

1. 시간을 위한 selectDogWithTimeState를 새로 만들고, 홈프래그먼트에서는 endDateTime만 갖다 쓰며 DataFormatter를 활용하여 '몇시간전' 로직을 구현했습니다.
2. 산책 기록이 없을 경우에도 예외 처리를 했습니다.
3. 레이아웃은 원래 다른 분이 하셨어서 많이 안건드렸습니다.

💭 추가 하고 싶은 부분
selectDogState, dogData.name를 활용해서 아래 사진처럼
선택된 강아지의 그래프임을 textview로 보여주듯이, '8시간 전'이 아닌 'rt:  8시간 전' 이렇게 표현하고 싶은데 어떻게 하면 좋을까요?

📖 참고 사항
![스크린샷 2024-06-26 오후 7 03 26](https://github.com/nbc-final-team2/ddaraogae/assets/89888486/6d3a3c87-38b3-4367-b97c-c9e84da1ad44)
![스크린샷 2024-06-26 오후 7 03 31](https://github.com/nbc-final-team2/ddaraogae/assets/89888486/63cdeba6-1642-4739-8beb-2630eb3f7c50)

**Comment by neoneoneo123** [comment]
강아지 이름이 이미지 아래에 있는데,
별도로 강아지 이름을 산책 시간 전에 한 번 더 보여줄 필요가 있을까요?

중복된 정보가 화면 안에 표시되는 것 같아서요..!

**Comment by theBettor** [comment]
오 그러네요 생각해보니... 뭔가 어떤 강아지의 마지막 산책시간임을 보여주기 위한 의도였는데 더 좋은 아이디어가 있을까요?
