### ISSUE TITLE
[질문] 버튼 아이디어가 필요해요

### ISSUE THREAD

**Issue by theBettor** [nbc-final-team2/ddaraogae#45]
💎 이슈 내용

Button 하나로 시작, 종료버튼을 구현할 수 있으면 좋겠습니다.
1. '시작' 버튼을 누르면 tracking이 시작됩니다.
2. 시작됨과 동시에 시작 버튼의 텍스트는 '종료'로 바뀝니다.
3. 종료 버튼을 누르면 다음 액티비티 화면으로 넘어갑니다.

📖 참고 사항

아이디어가 있으신분들 알려주세요!
사진의 Next 버튼은 좌표 데이터와 같이 넘기기 위해 임시로 만들어둔 버튼 입니다!
![Uploading Screenshot_20240607_141939.png…]()

중요한점
로직 빼는거 희광님이랑 하고 다시 전달드리겠습니다
서비스 파트에서 논의 필요

**Comment by winteryy** [comment]
산책 중인지 아닌지 상태를 저장하는 프로퍼티가 ViewModel 내에 존재해야 할 것 같습니다.
그걸 이용해서 UI의 변화(버튼 텍스트 변경 등)이 필요해보이니 LiveData나 Flow를 이용해 UI에서 관찰하는 형태로 구성해야 할 것 같고
ViewModel내에서 버튼이 눌렸을 때 취할 동작을 메소드를 정의하되, 해당 상태값을 참조해서 산책 중일 때와 아닐 때로 나누어 로직을 처리해볼 수 있을 것 같습니다
