### ISSUE TITLE
[QUESTION] 카메라 줌 잡는 로직 관련 질문

### ISSUE THREAD

**Issue by theBettor** [nbc-final-team2/ddaraogae#85]
💎 개발할 기능

<img width="802" alt="스크린샷 2024-06-13 오후 4 48 51" src="https://github.com/nbc-final-team2/ddaraogae/assets/89888486/bae5d319-f22b-47dc-bc0e-bfdb130f2a80">

아래와 같이 거리 차이 변수와 줌 레벨 변수 만들어서 줌을 동적으로 컨트롤하고 싶은데 잘 안되네요
저기 diif변수가 쓸모 없는 로직이라 그런 것 같은데 아이디어가 필요합니다.

<img width="905" alt="스크린샷 2024-06-13 오후 4 52 53" src="https://github.com/nbc-final-team2/ddaraogae/assets/89888486/70f1fb02-d2d3-4b82-b41f-065559417136">

📖 참고 사항

**Comment by winteryy** [comment]
`getDistance()`에 파라미터 잘못 들어가고 있는 것 같습니다 lat1, lng1, lat2, lng2 순서 아닌가요?

**Comment by theBettor** [comment]
주신 방법대로도 해봤는데 그래도 그대로입니다.
<img width="601" alt="스크린샷 2024-06-13 오후 5 27 06" src="https://github.com/nbc-final-team2/ddaraogae/assets/89888486/10679945-f44d-4583-9d14-2fa5bb4241c2">

**Comment by winteryy** [comment]
일단 이렇게만 봐서는 어디서 문제가 생기는지 잘 모르겠습니다
로그 찍어서 distanceDiff 값이 정상적으로 계산되는지, zoomLevel도 그에 맞게 잘 변환되는지 확인해주세요
