### ISSUE TITLE
[QUESTION] 런타임 권한 요청

### ISSUE THREAD

**Issue by theBettor** [nbc-final-team2/ddaraogae#93]
💎 개발할 기능

1. 권한 요청이 잘 되는지 안되는지 여부는 어떻게 알 수 있나요?
- 뭔가 데이터 다 리셋 시켜서 앱을 처음 쓸때 처음 권한 요청하는 다이어로그 같은걸 볼 수 있을까?
2. https://developer.android.com/training/permissions/requesting?hl=ko#kotlin 이것도 보고 다른 블로그도 보는데... 할때마다 퍼미션 관련 부분에서 에러가 떠서 진전이 없습니다.
3. override fun onRequestPermissionsResult를 꼭 써야하는 것 같습니다. 근데 어차피 에러가 발생해서 지금은 빠져 있습니다.
<img width="755" alt="스크린샷 2024-06-14 오전 2 20 56" src="https://github.com/nbc-final-team2/ddaraogae/assets/89888486/93080109-1e0d-4563-b52b-dc09acf36fd7">

<img width="796" alt="스크린샷 2024-06-14 오전 2 21 14" src="https://github.com/nbc-final-team2/ddaraogae/assets/89888486/5d634d12-249a-4f2a-a443-a30b21b5bf09">

지금 작업하는 사진과 이전에 작업했었던 사진 첨부합니다.
자세한건 제 브랜치를 checkout해서 확인해주세요.
📖 참고 사항

**Comment by winteryy** [comment]
1. 권한 처리는 매번 설정에 들어가서 획득 권한을 해제하거나, 앱 삭제 이후 재설치로 테스트해야 할 것 같습니다

2, 3. onRequestPermissionsResult를 구현하는 방식보다 requestPermissionLauncher를 이용하는 방식이 더 좋을 것 같습니다.
지금은 두 방식이 혼재되어 있는 것처럼 보입니다!
